### ISSUE TITLE
About openpose with TensorRT

### ISSUE THREAD

**Issue by guods** [zerollzeng/tiny-tensorrt#1]
Thanks for your work, Could you share more information about openpose with tensorRt?

**Comment by zerollzeng** [comment]
sorry for late reply, I can publish whole openpose source code now due to work reason, It has a complicated post-processing phase including resize, nms and body-part-connect, but a little hint for you is you can use the source code of official openpose, just extract relative function and make a little modification.

**Comment by zerollzeng** [comment]
now openpose is available, please refer tensorrt-zoo, it can support fp32 and fp16
