### ISSUE TITLE
onnx plugin

### ISSUE THREAD

**Issue by jianxiezhendong** [zerollzeng/tiny-tensorrt#32]
Now I have a onnx model, I want make a plugin targets to onnx.But I do not know how to achieve it. Do you have an Idea?

**Comment by zerollzeng** [comment]
you might refer to https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#extending, although the onnx plugin is very similiar to caffe plugin

**Comment by jinfagang** [comment]
@zerollzeng Hi, instead of surgeon on onnx file add some ops into it, I want wrap all postprocess into a plugin and add it to onnx network when parse it. Do u have any suggestion how to able to do this?

For instance, in yolo, you have already YoloLayer plugin, if my onnx just export the previous part model of yolo except yolo layer, then I want plug this plugin after onnx parsed network, what should I do exactly? thanks!

**Comment by zerollzeng** [comment]
@jinfagang Sorry for the late reply, I was on vacation these days.

> For instance, in yolo, you have already YoloLayer plugin, if my onnx just export the previous part model of yolo except yolo layer, then I want plug this plugin after onnx parsed network, what should I do exactly? thanks!

To achieve your purpose, modification of onnx model is necessary, for your example:
step 1: add a node n to your onnx model M, then your model would look like M--->n. you can done this by several tools. eg. TensorRT release 7.22 add a  [onnx-graphsurgeon](https://github.com/NVIDIA/TensorRT/tree/master/tools/onnx-graphsurgeon).
step 2: implement your plugin and register it.

**Comment by jinfagang** [comment]
@zerollzeng thank u for your suggestion. I think evolving onnx model modifcation is very complicated. I am currently try add plugins directly after the output of network when  onnx parsed it.
then serialized the model to local, to see if it can work not.
