### ISSUE TITLE
yolov5s int8量化不出框？

### ISSUE THREAD

**Issue by Wulingtian** [zerollzeng/tiny-tensorrt#37]
您好，fp32测试是正常出框的，int8量化后不出框是怎么回事？

**Comment by zerollzeng** [comment]
Thanks for trying tiny-tensorrt
But unfortunally I can help you since I don't familiar with yolov5s :). there are some ways you can try, compare the fp32 and int8 output on some middle layer until you find the outputs that's differ a lot. once you get the answer, file an issue to offcial TensorRT repo.
